fix NoSuchMethodError for Minecraft.getInstance
refactor code to
a) get the Minecraft instance lazily in the MumbleInitializer loop thread by simply catching the exception
b) store the Minecraft instance in the MumbleLinkBase class
c) provide a getter for the stored instance on MumbleLinkBase to use
     instead

up the version fix number
fix wrong EOL format for mods.toml
add version variable to mods.toml so that it is generated for MumbleLink